# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 08:14
from __future__ import unicode_literals

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('hashtag_subscription', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name=b'image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=datetime.datetime(2016, 12, 3, 8, 22, 39, 410155, tzinfo=utc), null=True)),
                ('image_author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('image_tags', models.ManyToManyField(to='hashapp.HashTagModel')),
            ],
        ),
    ]
