# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='published_date',
            field=models.DateTimeField(blank=datetime.datetime(2016, 11, 27, 10, 18, 43, 440417, tzinfo=utc), null=True),
        ),
    ]
