# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-02 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hashapp', '0002_auto_20161127_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='tags',
            new_name='image_tags',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='published_date',
            field=models.DateTimeField(blank=datetime.datetime(2016, 12, 2, 5, 32, 35, 620335, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='hashtagmodel',
            name='hashtag_subscription',
            field=models.ManyToManyField(to='hashapp.UserModel'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_author',
            field=models.ManyToManyField(to='hashapp.UserModel'),
        ),
    ]
